collated: true
label: Notices
notes: Use to alert the user about a current or potential outcome such as success, failure or a warning.
context:
  linkMessage: <a href="#">Links are styled to match</a>
variants:
  - name: default
    label: Info  
    context:
      modifier: default
      notice:
        heading: Informational Notice
        message: This is a default notice.
  - name: Success
    label: Success  
    context:
      modifier: success
      notice:
        heading: Success Notice
        message: This is a success notice.
  - name: Warning
    label: Warning  
    context:
      modifier: warning
      notice:
        heading: Warning Notice
        message: This is a warning notice.
  - name: Error
    label: Error  
    context:
      modifier: error
      notice:
        heading: Error Notice
        message: This is an error notice.
