label: Implied
notes: Use to hide content that would be implied for visual users, such as in "read more" links. (idea swiped from the css of informationarchitects.jp)
context:
  visible: Read more
  implied: about jackelopes.