context:
  lines:
    - line:
       - size: 2 
       - size: 1 
       - size: 1 
    - line:
       - size: 1 
       - size: 1 
    - line:
       - size: 1 
       - size: 1 
       - size: 1 
    - line:
       - size: 1 
       - size: 1 
       - size: 1 
       - size: 1 
    - line:
       - size: 3 
       - size: 1 