context:
  one-one:
    modifier: half
    label: First Name
    name: first
    id: first
  one-two:
    modifier: half
    label: Last Name
    name: last
    id: last
  two-one:
    modifier: full
    label: Address
    name: address
    id: address
  three-one:
    modifier: half
    label: City
    name: city
    id: city
  three-two:
    modifier: fourth
    label: State
    name: state
    id: state
  three-three:
    modifier: fourth
    label: Zip
    name: zip
    id: zip
  four:
    modifier: third
    label: 1/3
    name: third
    id: third

