collated: true
context:
  text: Link
  url: "https://kljasdfkljasasdfasfasdfasklkjikuiou.com"
  separator: "<br>"
variants:
  - name: visited
    context:
      modifier: visited
  - name: hover
    context:
      modifier: hover
  - name: focus
    context:
      modifier: focus
  - name: active
    context:
      modifier: active
  - name: new tab
    context:
      target: "_blank"