label: Intrinsic Media
collated: true
notes: Defines image or iframe-embedded video size even before the media loads. Minimizes page repaints, reflows and maintains aspect ratio on screen resize. See http://daverupert.com/2015/12/intrinsic-placeholders-with-picture/
 