notes: Constrains elements to a max width and centers itself horizontally.
context:
  text: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio cupiditate aperiam blanditiis! Provident repellendus, at eaque pariatur quidem optio dicta aliquam tempore commodi, excepturi neque et, facilis rem. Inventore, eaque.