context:
  item:
    - term: term
      definition: definition
    - term: term
      definition: definition
    - term: term
      definition: definition
    - term: term
      definition: definition
    - term: term
      definition: definition
    - term: term
      definition: definition
    - term: term
      definition: definition