context:
  checkboxes:
    - label: Strawberries
      id: Strawberries
      name: fruit
      value: strawberries
    - label: Grapes
      id: grapes
      name: fruit
      value: grapes
    - label: Blueberries
      id: blueberries
      name: fruit
      value: blueberries

