notes: A list of radio or checkbox inputs
label: Radio/Checkbox List
context:
  legend: A List of Choices
  choices:
    - label: Choice 1
      id: c1
      name: choice
      value: c1
    - label: Choice 2 (with a really long description... Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ad expedita eius atque quae ab vel mollitia ut vero deserunt natus quasi debitis molestias, suscipit eligendi itaque fugit soluta sit deleniti.)
      id: c2
      name: choice
      value: c2
    - label: Choice 3
      id: c3
      name: choice
      value: c3
