collated: true
context:
  label: Full width 
  id: input-full
  name: input
  modifier: full
variants:
  - name: half
    context: 
      label: 1/2 width
      id: input-half
      name: input-half
      modifier: half     
  - name: third
    context: 
      label: 1/3 width
      id: input-third
      name: input-third
      modifier: third     
  - name: two-thirds
    context: 
      label: 2/3 width
      id: input-two-thirds
      name: input-two-thirds
      modifier: two-thirds
  - name: fourth
    context: 
      label: 1/4 width
      id: input-fourth
      name: input-fourth
      modifier: fourth     
  - name: three-fourths
    context: 
      label: 3/4 width
      id: input-three-fourths
      name: input-three-fourths
      modifier: three-fourths
